Revert to Hugo 0.151.2 to avoid breaking change in 0.152.0
Starting from Hugo 0.152.0, non-project module mounts must be local paths.

We're hitting the below error, don't have time to fix so reverting to prior version for now:

Error: command error: failed to load modules: invalid module config for "github.com/google/docsy": "../../node_modules/bootstrap": mount source must be a local path for modules/themes